name: Build release APK
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "10G"
      CCACHE_HARDLINK: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: DamianReeves/write-file-action@master
        with:
          path: ./API_KEYS
          contents: |
            APP_ID = 6
            APP_HASH = "eb06d4abfb49dc3eeb1aeb98ae0f581e"
            MAPS_V2_API = 0

            SIGNING_KEY_PASSWORD = ${{ secrets.SIGNING_KEY_PASSWORD }}
            SIGNING_KEY_ALIAS = ${{ secrets.SIGNING_KEY_ALIAS }}
            SIGNING_KEY_STORE_PASSWORD = ${{ secrets.SIGNING_KEY_PASSWORD }}
          write-mode: overwrite

      - name: Write google-services.json
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: google-services.json
          fileDir: ./TMessagesProj
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON_FILE_IN_BASE64 }}

      - name: Write signing keystore file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: extera.jks
          fileDir: ./TMessagesProj/config
          encodedString: ${{ secrets.SIGNING_KEYSTORE_FILE_IN_BASE64 }}

      - name: Update packages
        run: sudo apt-get update

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle Build
        uses: actions/cache@v3

